import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  // NON FRICTION SELF-HELP BOOK
  {
   _id: uuid(),
    Quantity : 1,
    title: "Doglapan",
    author: "Ashneer Grower",
    price: "299",
    discount: "20%",
    intprice: "400",
    categoryName: "Non-Friction",
    image: "https://99booksstore.com/uploaded_files/product/381978600.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Life Amazing Secret",
    author: "Gour Gopal Das",
    price: "199",
    discount: "50%",
    intprice: "400",
    categoryName: "Non-Friction",
    image:"https://cloudfront.penguin.co.in/wp-content/uploads/2022/12/9780143442295.jpg",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Hacking Health",
    author: "Mukesh Bansal",
    price: "149",
    discount: "40%",
    intprice: "349",
    categoryName: "Non-Friction",
    image:"https://cloudfront.penguin.co.in/wp-content/uploads/2023/01/9780670097135.jpg",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "99 Not out",
    author: "Sujata Kelkar Shetty",
    price: "229",
    discount: "30%",
    intprice: "420",
    categoryName: "Non-Friction",
    image:"https://cloudfront.penguin.co.in/wp-content/uploads/2022/11/9780143442417.jpg",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "50 Toughest Questions of Life",
    author: "Deepak Ramola",
    price: "149",
    discount: "50%",
    intprice: "300",
    categoryName: "Non-Friction",
    image:"https://cloudfront.penguin.co.in/wp-content/uploads/2022/11/9780143451044.jpg",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Ask the Monk",
    author: "Nityanand Charan Das",
    price: "249",
    discount: "10%",
    intprice: "259",
    categoryName: "Non-Friction",
    image:"https://penguin.co.in/wp-content/uploads/2022/10/9780143459026-194x300.jpg",
  },
 {
   _id: uuid(),
    Quantity : 1,
    title: "The Power of Thoughts",
    author: "Swami Mukundananada",
    price: "259",
    discount: "30%",
    intprice: "299",
    categoryName: "Non-Friction",
    image:"https://penguin.co.in/wp-content/uploads/2023/01/9780143452331-195x300.jpg",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Equal, yet Different",
    author: "Anita Bhogle",
    price: "189",
    discount: "40%",
    intprice: "300",
    categoryName: "Non-Friction",
    image: "https://cloudfront.penguin.co.in/wp-content/uploads/2022/10/9780143459279.jpg",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Atomic Habits",
    author: "James Clear",
    price: "139",
    discount: "20%",
    intprice: "260",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/456818251.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: "139",
    discount: "30%",
    intprice: "240",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/284481191.webp",
  },
  {
   _id: uuid(),
   Quantity : 1,
    title: "The Power of Subconscious Mind",
    author: "Joseph Murphy",
    price: "99",
    discount: "50%",
    intprice: "200",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/449162314.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Ikigai",
    author: "Hector Garcia",
    price: "149",
    discount: "40%",
    intprice: "320",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/442605415.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "SECRET",
    author: "Rhonda Byrne",
    price: "159",
    discount: "30%",
    intprice: "300",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/340067336.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Get Epic Shit Done",
    author: "Ankur Warikoo",
    price: "129",
    discount: "40%",
    intprice: "300",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/367710075.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Think And Grow Rich",
    author: "Napoleon Hill",
    price: "109",
    discount: "50%",
    intprice: "220",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/102708107.webp",
  },
  {
   _id: uuid(),
    Quantity : 1,
    title: "Do Epic Shit",
    author: "Ankur Warikoo",
    price: "189",
    discount: "20%",
    intprice: "300",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/330071619.webp",
  },
{
  _id: uuid(),
    Quantity : 1,
    title: "Mindset",
    author: "Dr. Carol's Dwick",
    price: "199",
    discount: "40%",
    intprice: "290",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/365145840.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Mountain is You",
    author: "Brianna Wiest",
    price: "169",
    discount: "50%",
    intprice: "400",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/182360827.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Subtle Art of Not Giving F*ck",
    author: "Mark Mansion",
    price: "149",
    discount: "20%",
    intprice: "300",
    categoryName: "Non-Friction",
    image:"https://99booksstore.com/uploaded_files/product/112423815.webp",
  },


// ---------------------

//  Friction

// ---------------------

{
_id: uuid(),
 Quantity : 1,
    title: "Ram-Scion of Ikshvaku",
    author: "Amish Tripathi",
    price: "179",
    discount: "20%",
    intprice: "400",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/395761793.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    price: "499",
    discount: "20%",
    intprice: "430",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/211194746.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Warren Buffett Way",
    author: "Robert G. Hagstrom",
    price: "299",
    discount: "10%",
    intprice: "320",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/261849238.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "Welcome Home",
    author: "Najwa Zebian",
  price: "219",
    discount: "20%",
    intprice: "400",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/477656731.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "Think Like A Monk",
    author: "Jay Shetty",
  price: "189",
    discount: "10%",
    intprice: "400",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/407898631.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The 5 Am CLUB",
    author: "Robin Sharma",
  price: "199",
    discount: "30%",
    intprice: "290",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/407061802.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "Eat That Frog",
    author: "Brain Tracy",
  price: "129",
    discount: "10%",
    intprice: "199",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/193382715.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Making Of Manager",
    author: "Julie Zhuo",
  price: "179",
    discount: "20%",
    intprice: "300",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/103251870.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
  price: "189",
    discount: "30%",
    intprice: "359",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/121866165.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "Energize your Mind",
    author: "Gaur Gopal Das",
  price: "149",
    discount: "40%",
    intprice: "329",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/327378190.webp",
  },
{
_id: uuid(),
 Quantity : 1,
    title: "The Hardest Fall",
    author: "Ella Maise",
  price: "369",
    discount: "50%",
    intprice: "650",
    categoryName: "Friction",
    image:"https://99booksstore.com/uploaded_files/product/477627329.webp",
  },

  

// {
// _id: uuid(),
//     title: "",
//     author: "",
//     price: "",
//     categoryName: "Friction",
//     discount: "20%",
//     intprice: "400",
// 
//     image:"",
//   },



  // HORROR BOOK
  {
   _id: uuid(),
 Quantity : 1,
    title: "From Blood AND ASH",
    author: "Jennifer armentrout",
    price: "1168",
    discount: "50%",
    intprice: "2900",
    categoryName: "Horror",
    image:"https://99booksstore.com/uploaded_files/product/265371573.webp",
  },
  {
   _id: uuid(),
 Quantity : 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: "139",
    discount: "20%",
    intprice: "300",
    categoryName: "Friction",
    image: "https://images.gr-assets.com/books/1361975680l/2657.jpg"
  },
  
];
